#!/bin/bash

pip install jupyter_contrib_nbextensions
pip install jupyter_nbextensions_configurator
pip install numpy

jupyter contrib nbextension install --user
jupyter nbextensions_configurator enable --user
jupyter nbextension enable hide_input_all/main
jupyter nbextension enable python-markdown/main
